import Head from "next/head";
import type { NextPage } from "next";
import { useContext } from "react";
import { Button, Grid, Typography } from "@mui/material";
import { motion } from "framer-motion";
import { MobileStateContext } from "../../contexts/MobileContexts";
import Events from "../../components/studentliv/Events";
import ImageCarousel from "../../components/studentliv/ImageCarousel";
import gruppbild from "../../public/images/gruppbild.jpg";
import nollePImage from "../../public/images/nollep.jpg";
import Studentkonto from "../../components/studentliv/Studentkonto";
import fiket from "../../public/images/fiket.jpg";
import BackgroundImage from "../../components/general/BackgroundImage";
import Image from "next/image";
import StyledButton from "../../components/general/StyledButton";

const StudentlivPage: NextPage = () => {
  const { isMobile, isIpad, isDesktop } = useContext(MobileStateContext);
  return (
    <motion.div exit={{ opacity: 0 }} initial="initial" animate="animate">
      <Head>
        <title>Medieteknik | Studentliv</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container sx={{ justifyContent: "center" }}>
        <BackgroundImage pageName="STUDENTLIV" imgSrc={gruppbild.src} />

        <Grid
          container
          spacing={3}
          sx={[
            {
              marginTop: "50px",
              p: 3,
            },
            // isDesktop ? { width: "70%" } : { width: "100%" },
          ]}
        >
          <Grid
            item
            xs={12}
            md={6}
            sx={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
            }}
          >
            <ImageCarousel />
          </Grid>
          <Grid
            item
            xs={12}
            md={6}
            sx={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              textAlign: "center",
            }}
          >
            <Typography variant="h2" sx={{ m: 2 }}>
              Bostad
            </Typography>
            <Typography sx={{ m: 2 }}>
              Som student i Norrköping finns det flera olika boendemöjligheter.
              Studentbo i Norrköping tillhandahåller flera olika boenden med
              gångavstång till Campus. Om du funderar på att börja plugga i
              Norrköping kan du ställa dig i kö direkt.
              <br />
              <br />
              Det finns även bra pendlingsmöjligheter från Linköping.
              Campusbussen är gratis för alla studenter och åker mellan Campus
              US, Campus Valla och Campus Norrköping.
            </Typography>
            {/* <Button
              target="_blank"
              href="https://hyresbostader.se/studentbo"
              variant="contained"
              color="secondary"
              sx={{ marginTop: 2, marginBottom: "30px" }}
            ></Button> */}
            <StyledButton
              src="https://hyresbostader.se/studentbo"
              external={true}
            >
              Till studentbo.se
            </StyledButton>
          </Grid>
        </Grid>
        <Grid container sx={{ paddingTop: 3, paddingBottom: 3 }}>
          <img
            src={nollePImage.src}
            style={{ height: "30vh", width: "100%", objectFit: "cover" }}
          />
        </Grid>

        <Grid
          sx={[
            { textAlign: "center", p: 3 },
            isDesktop ? { width: "60%" } : { width: "90%" },
          ]}
        >
          <Typography variant="h2">Nolle-P</Typography>
          <Typography>
            De flesta som pluggar här flyttar hemifrån för att komma till
            Norrköping och det kan kännas rätt läskigt att lämna allt man vuxit
            upp med. Men oroa dig inte, det som väntar här är vad de flesta på
            MT minns som den bästa delen av deras studietid: Nolleperioden,
            eller Nolle-P. Nolle-P heter så eftersom de nya eleverna inte börjar
            ettan innan sista dagen på Nolle-P. Under Nolle-P får du lära känna
            alla andra MT:are, göra stela lära-känna-varandra-aktiviteter,
            festa, fräscha upp gymnasiematten, och bekanta dig med LiUs
            studentkultur och -traditioner.
          </Typography>
        </Grid>
        <Grid container sx={{ marginTop: 3, marginBottom: 3 }}>
          <Studentkonto />
        </Grid>

        <Grid
          container
          sx={[
            { textAlign: "center" },
            isDesktop && { width: "50%" },
            isIpad && { width: "70%" },
          ]}
        >
          <Typography variant="h2" sx={{ textAlign: "center", width: "100%" }}>
            Nöjen
          </Typography>
          <Grid
            container
            // direction="row"
            justifyContent="center"
            alignItems="center"
          >
            <Grid item xs={4} sx={{ p: 3 }}>
              <img
                src={fiket.src}
                width="100%"
                style={{
                  borderRadius: "10px",
                  objectFit: "contain",
                  boxShadow: "3px 3px 5px 2px #d9d9d9",
                }}
              />
            </Grid>
            <Grid item xs={4} sx={{ p: 3 }}>
              <img
                src={fiket.src}
                width="100%"
                style={{
                  borderRadius: "10px",
                  objectFit: "contain",
                  boxShadow: "3px 3px 5px 2px #d9d9d9",
                }}
              />
            </Grid>
            <Grid item xs={4} sx={{ p: 3 }}>
              <img
                src={fiket.src}
                width="100%"
                style={{
                  borderRadius: "10px",
                  objectFit: "contain",
                  boxShadow: "3px 3px 5px 2px #d9d9d9",
                }}
              />
            </Grid>
          </Grid>
          <Typography
            variant="h3"
            sx={{ textAlign: "center", width: "100%", marginBottom: "18px" }}
          >
            Sektionens event
          </Typography>
          <Typography sx={{ textAlign: "center", width: "100%" }}>
            Kanske någon text här
          </Typography>
          <Events />
        </Grid>
      </Grid>
    </motion.div>
  );
};

export default StudentlivPage;
