import Head from "next/head";
import type { NextPage } from "next";
import { useContext } from "react";
import { Button, Grid, Typography } from "@mui/material";
import { motion } from "framer-motion";
import { MobileStateContext } from "../../contexts/MobileContexts";
import Events from "../../components/studentliv/Events";
import ImageCarousel from "../../components/studentliv/ImageCarousel";
import gruppbild from "../../public/images/gruppbild.jpg";
import nollePImage from "../../public/images/nollep.jpg";
import Studentkonto from "../../components/studentliv/Studentkonto";
import fiket from "../../public/images/fiket.jpg";
import BackgroundImage from "../../components/general/BackgroundImage";
import Image from "next/image";
import StyledButton from "../../components/general/StyledButton";
import ImageWithSummary from "../../components/general/ImageWithSummary";

const StudentlivPage: NextPage = () => {
  const { isMobile, isIpad, isDesktop } = useContext(MobileStateContext);
  return (
    <motion.div
      exit={{ opacity: 0 }}
      initial="initial"
      animate="animate"
      style={{ overflow: "hidden", background: "white" }}
    >
      <Head>
        <title>Medieteknik | Studentliv</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container sx={{ justifyContent: "center" }}>
        <BackgroundImage pageName="STUDENTLIV" imgSrc="/images/nollep5.jpg" />

        {/* <Grid
          container
          spacing={3}
          sx={[
            {
              marginTop: "50px",
              p: 3,
            },
            // isDesktop ? { width: "70%" } : { width: "100%" },
          ]}
        >
          <Grid
            item
            xs={12}
            md={6}
            sx={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
            }}
          >            
            <Image
              src="/images/eventPictures/midsommar.jpg"
              height="100px"
              width="100px"
            />
          </Grid>
          <Grid
            item
            xs={12}
            md={6}
            sx={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              textAlign: "center",
            }}
          >
            <Typography variant="h2" sx={{ m: 2 }}>
              Bostad
            </Typography>
            <Typography sx={{ m: 2 }}>
              Som student i Norrköping finns det flera olika boendemöjligheter.
              Studentbo i Norrköping tillhandahåller flera olika boenden med
              gångavstång till Campus. Om du funderar på att börja plugga i
              Norrköping kan du ställa dig i kö direkt.
              <br />
              <br />
              Det finns även bra pendlingsmöjligheter från Linköping.
              Campusbussen är gratis för alla studenter och åker mellan Campus
              US, Campus Valla och Campus Norrköping.
            </Typography>
            <StyledButton
              src="https://hyresbostader.se/studentbo"
              external={true}
            >
              Till studentbo.se
            </StyledButton>
          </Grid>
        </Grid> */}
        <ImageWithSummary
          imageSrc="/images/eventPictures/midsommar.jpg"
          imgWidth="700px"
          imgHeight="700px"
          direction="row"
        >
          <Grid
            sx={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              textAlign: "center",
            }}
          >
            <Typography variant="h2" sx={{ m: 2 }}>
              Bostad
            </Typography>
            <Typography sx={{ m: 2 }}>
              Som student i Norrköping finns det flera olika boendemöjligheter.
              Studentbo i Norrköping tillhandahåller flera olika boenden med
              gångavstång till Campus. Om du funderar på att börja plugga i
              Norrköping kan du ställa dig i kö direkt.
              <br />
              <br />
              Det finns även bra pendlingsmöjligheter från Linköping.
              Campusbussen är gratis för alla studenter och åker mellan Campus
              US, Campus Valla och Campus Norrköping.
            </Typography>
            <StyledButton
              src="https://hyresbostader.se/studentbo"
              external={true}
            >
              Till studentbo.se
            </StyledButton>
          </Grid>
        </ImageWithSummary>
        <Grid container sx={{ paddingTop: 3, paddingBottom: 3 }}>
          <img
            src={"/images/nollep6.jpg"}
            style={{
              height: "50vh",
              width: "100%",
              objectFit: "cover",
              objectPosition: "center 25%",
            }}
          />
          <Typography
            sx={{
              textAlign: "right",
              width: "100%",
              marginTop: "-30px",
              color: "white",
              marginRight: "10px",
            }}
          >
            Foton: Sofia Krantz
          </Typography>
        </Grid>

        <Grid
          sx={[
            { textAlign: "center", p: 2, marginTop: 1, marginBottom: 7 },
            isDesktop ? { width: "60%" } : { width: "90%" },
          ]}
        >
          <Typography variant="h2">Nolle-P</Typography>
          <Typography>
            Under Nolle-P får du lära känna alla andra MT:are, göra stela
            lära-känna-varandra-aktiviteter, festa, fräscha upp gymnasiematten,
            och bekanta dig med LiUs studentkultur och -traditioner. Denna
            period pågår under två veckor och är ett perfekt tillfälle att
            bekanta dig med dina klasskompisar.
            <br />
            <br />
            Under Nolle-P anordnas aktiviter nästan varje lunch och kväll och
            under dagen är det fokus på plugg. Efter Nolle-P drar flera andra
            kurser igång och de roliga eventen sker lite mer utspritt!
            <br />
            <br />
            PS! Glöm inte matlådan ;)
          </Typography>
        </Grid>

        <Grid container sx={{ marginTop: 6, marginBottom: 6 }}>
          <Studentkonto />
        </Grid>

        <Grid
          container
          sx={[
            { textAlign: "center" },
            isDesktop && { width: "50%" },
            isIpad && { width: "70%" },
          ]}
        >
          {/* <Typography variant="h2" sx={{ textAlign: "center", width: "100%" }}>
            Nöjen
          </Typography> */}
          {/* <Grid
            container
            // direction="row"
            justifyContent="center"
            alignItems="center"
          >
            <Grid item xs={4} sx={{ p: 3 }}>
              <img
                src={fiket.src}
                width="100%"
                style={{
                  borderRadius: "10px",
                  objectFit: "contain",
                  boxShadow: "3px 3px 5px 2px #d9d9d9",
                }}
              />
            </Grid>
            <Grid item xs={4} sx={{ p: 3 }}>
              <img
                src={fiket.src}
                width="100%"
                style={{
                  borderRadius: "10px",
                  objectFit: "contain",
                  boxShadow: "3px 3px 5px 2px #d9d9d9",
                }}
              />
            </Grid>
            <Grid item xs={4} sx={{ p: 3 }}>
              <img
                src={fiket.src}
                width="100%"
                style={{
                  borderRadius: "10px",
                  objectFit: "contain",
                  boxShadow: "3px 3px 5px 2px #d9d9d9",
                }}
              />
            </Grid>
          </Grid> */}
          <Typography
            variant="h2"
            sx={{ textAlign: "center", width: "100%", marginBottom: "18px" }}
          >
            Sektionens event
          </Typography>
          <Typography sx={{ textAlign: "center", width: "100%" }}>
            Utöver allmänna event anordrar styrelsen under året event för endast
            MT-studenter. Flera av dessa event anordas med hjälp av olika
            utskott som består av engagerade MT-studenter. Exempel på utskott är
            event- och midsommarutskottet.
          </Typography>
          <Events />
        </Grid>
      </Grid>
    </motion.div>
  );
};

export default StudentlivPage;
