import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRef } from "react";
import gruppbild from "../assets/gruppbild.jpg";
import { motion } from "framer-motion";
import Navigation from "../components/navigation/Navigation";
import {
  ListItemText,
  Box,
  Typography,
  List,
  Grid,
  ListItem,
  Drawer,
  IconButton,
} from "@mui/material";
import { fadeInUp } from "../animations/constants";
import BackgroundImage from "../components/general/BackgroundImage";

const Home: NextPage = () => {
  const constraintsRef1 = useRef(null);
  const constraintsRef2 = useRef(null);
  const constraintsRef3 = useRef(null);
  const constraintsRef4 = useRef(null);

  return (
    <motion.div
      // style={{
      //   backgroundImage: `url(${gruppbild.src})`,
      //   backgroundSize: "cover",
      // }}
      animate="animate"
      initial="initial"
    >
      <Head>
        <title>Civilingenjör i Medieteknik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <video autoPlay loop muted id="video">
        <source
          src={require(`../assets/introVideo.mp4`).default.src}
          type="video/mp4"
        />
      </video> */}
      <BackgroundImage imgSrc={gruppbild.src}>
        <Grid
          display="flex"
          flexDirection="column"
          alignItems="center"
          justifyContent="center"
          sx={{ width: "100%", height: "80vh", zIndex: 100 }}
        >
          <Grid
            container
            display="flex"
            alignItems="center"
            justifyContent="center"
          >
            <motion.div ref={constraintsRef1} variants={fadeInUp}>
              <motion.div
                drag
                dragConstraints={constraintsRef1}
                style={{
                  backgroundColor: "#EC6610",
                  width: "150px",
                  height: "150px",
                }}
              />
            </motion.div>
            <div style={{ margin: "20px" }}></div>
            <motion.div ref={constraintsRef2}>
              <motion.div
                drag
                dragConstraints={constraintsRef2}
                style={{
                  backgroundColor: "#3b484f",
                  width: "150px",
                  height: "150px",
                }}
              />
            </motion.div>
          </Grid>
          <div style={{ margin: "10px" }}></div>
          <motion.div ref={constraintsRef3}>
            <motion.div
              drag
              dragConstraints={constraintsRef3}
              style={{
                fontFamily: "Lato",
                fontSize: "45px",
              }}
            >
              CIVILINGENJÖR
            </motion.div>
          </motion.div>
          <motion.div ref={constraintsRef4}>
            <motion.div
              drag
              dragConstraints={constraintsRef4}
              style={{
                fontFamily: "Barlow",
                fontWeight: "bold",
                fontSize: "64px",
              }}
            >
              MEDIETEKNIK
            </motion.div>
          </motion.div>
        </Grid>
      </BackgroundImage>
      <Typography variant="h1" sx={{ p: "60px" }}>
        Hem
      </Typography>
    </motion.div>
  );
};

export default Home;
