import { Typography } from "@mui/material";

import Grid from "@mui/material/Unstable_Grid2";

import { motion } from "framer-motion";
import type { NextPage } from "next";
import type { Value } from "../utils/types";
import Head from "next/head";
import { useRef } from "react";
import { fadeInUp } from "../animations/constants";
import gruppbild from "../assets/gruppbild.jpg";
import BackgroundImage from "../components/general/BackgroundImage";
import jsonValues from "../content/values.json";
import MtValues from "../components/home/mtValues";



const Home: NextPage = () => {
  const constraintsRef1 = useRef(null);
  const constraintsRef2 = useRef(null);
  const constraintsRef3 = useRef(null);
  const constraintsRef4 = useRef(null);

  const values: Value[] = jsonValues;

  return (
    <>
      <motion.div
        // style={{
        //   backgroundImage: `url(${gruppbild.src})`,
        //   backgroundSize: "cover",
        // }}
        animate="animate"
        initial="initial"
        style={{ overflow: "hidden" }}

      >
        <Head>
          <title>Civilingenjör i Medieteknik</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* <video autoPlay loop muted id="video">
        <source
          src={require(`../assets/introVideo.mp4`).default.src}
          type="video/mp4"
        />
      </video> */}
        <BackgroundImage imgSrc={gruppbild.src}>
          {
            //TODO: This grid should cover entire page and contian all child grids 
          }
          <Grid
            display="flex"
            flexDirection="column"
            alignItems="center"
            justifyContent="center"
            sx={{ width: "100%", height: "80vh", zIndex: 100 }}
          >
            <Grid
              container
              display="flex"
              alignItems="center"
              justifyContent="center"
            >
              <motion.div ref={constraintsRef1} variants={fadeInUp}>
                <motion.div
                  drag
                  dragConstraints={constraintsRef1}
                  style={{
                    backgroundColor: "#EC6610",
                    width: "150px",
                    height: "150px",
                  }}
                />
              </motion.div>
              <div style={{ margin: "20px" }}></div>
              <motion.div ref={constraintsRef2}>
                <motion.div
                  drag
                  dragConstraints={constraintsRef2}
                  style={{
                    backgroundColor: "#3b484f",
                    width: "150px",
                    height: "150px",
                  }}
                />
              </motion.div>
            </Grid>
            <div style={{ margin: "10px" }}></div>
            <motion.div ref={constraintsRef3}>
              <motion.div
                drag
                dragConstraints={constraintsRef3}
                style={{
                  fontFamily: "Lato",
                  fontSize: "45px",
                }}
              >
                CIVILINGENJÖR
              </motion.div>
            </motion.div>
            <motion.div ref={constraintsRef4}>
              <motion.div
                drag
                dragConstraints={constraintsRef4}
                style={{
                  fontFamily: "Barlow",
                  fontWeight: "bold",
                  fontSize: "64px",
                }}
              >
                MEDIETEKNIK
              </motion.div>
            </motion.div>
          </Grid>
        </BackgroundImage>
        <Grid container spacing={2} bgcolor={"white"}>
        <Grid xs={12}>
          <Typography textAlign={"center"} fontSize={34}>Vad är MT?</Typography>
        </Grid>
      </Grid>
      <Grid container padding={5} alignItems={"center"} spacing={6} columns={{ xs: 4, sm: 8, md: 12 }} bgcolor="white">
        {values.map((value, index) => (
          <Grid
            xs={4} 
            sm={4}
            md={4} 
            key={index}
            alignItems="center"
            justifyContent="center"
          >
            {/* TODO: center last item when screen is smaller*/}
            <MtValues description={value.description} title={value.title} image={value.image} />
          </Grid>
        ))}
      </Grid>
      </motion.div>
    </>
  );
};

export default Home;
