import Head from "next/head";
import type { NextPage } from "next";
import { useState, useContext } from "react";
import { Grid, Typography } from "@mui/material";
import { motion } from "framer-motion";
import { MobileStateContext } from "../../contexts/MobileContexts";
import Events from "../../components/studentliv/Events";
import ImageCarousel from "../../components/studentliv/ImageCarousel";

const StudentlivPage: NextPage = () => {
  const { isMobile, isIpad, isDesktop } = useContext(MobileStateContext);
  return (
    <motion.div exit={{ opacity: 0 }} initial="initial" animate="animate">
      <Head>
        <title>Medieteknik | Studentliv</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container sx={{ marginTop: "100px" }}>
        <Typography variant="h1" sx={{ textAlign: "center", width: "100%" }}>
          STUDENTLIV
        </Typography>
      </Grid>
      <Grid container>
        <ImageCarousel></ImageCarousel>
      </Grid>
      <Grid container>
        <Typography variant="h3" sx={{ textAlign: "center", width: "100%" }}>
          Sektionens event
        </Typography>
        <Events />
      </Grid>
    </motion.div>
  );
};

export default StudentlivPage;
