import { Typography, useMediaQuery, useTheme } from "@mui/material";
import Grid from "@mui/material/Unstable_Grid2";
import { motion } from "framer-motion";
import type { NextPage } from "next";
import Head from "next/head";
import { useContext, useEffect, useRef, useState } from "react";
import { fadeInUp } from "../animations/constants";
import BackgroundImage from "../components/general/BackgroundImage";
import ImageWithSummary from "../components/general/ImageWithSummary";
import StyledButton from "../components/general/StyledButton";
import WavyBackground from "../components/general/WavyBackground";
import Carousel from "../components/home/Carousel";
import MtValues from "../components/home/mtValues";
import carouselImages from "../content/carouselItems.json";
import jsonValues from "../content/values.json";
import { MobileStateContext } from "../contexts/MobileContexts";
import type { CarouselItem, Value } from "../utils/types";

const Home: NextPage = () => {
  const { isMobile, isIpad, isDesktop } = useContext(MobileStateContext);

  const [cubeWidth, setCubeWidth] = useState<string>("150px");

  useEffect(() => {
    if (isMobile) {
      setCubeWidth("70px");
    } else {
      setCubeWidth("150px");
    }
  }, [isMobile]);
  const theme = useTheme();
  console.log(cubeWidth);

  const constraintsRef1 = useRef(null);
  const constraintsRef2 = useRef(null);
  const constraintsRef3 = useRef(null);
  const constraintsRef4 = useRef(null);

  const matchesSm = useMediaQuery(theme.breakpoints.down("md"));
  const notSm = useMediaQuery(theme.breakpoints.not("sm"));

  const values: Value[] = jsonValues;
  const carouselItems: CarouselItem[] = carouselImages;

  return (
    <motion.div
      // style={{
      //   backgroundImage: `url(${gruppbild.src})`,
      //   backgroundSize: "cover",
      // }}
      animate="animate"
      initial="initial"
      style={{ overflow: "hidden", background: "white" }} //, display: "flex", flexDirection: "column", alignItems: "center"
    >
      <Head>
        <title>Civilingenjör i Medieteknik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <video autoPlay loop muted id="video">
        <source
          src={require(`../assets/introVideo.mp4`).default.src}
          type="video/mp4"
        />
      </video> */}
      <BackgroundImage imgSrc="/images/axels/styrelsen-6.webp">
        <Grid
          display="flex"
          flexDirection="column"
          alignItems="center"
          justifyContent="center"
          sx={{ width: "100%", height: "80vh", zIndex: 100 }}
        >
          <Grid
            container
            display="flex"
            alignItems="center"
            justifyContent="center"
          >
            <motion.div ref={constraintsRef1} variants={fadeInUp}>
              <motion.div
                drag
                dragConstraints={constraintsRef1}
                style={{
                  backgroundColor: "#EC6610",
                  width: cubeWidth,
                  height: cubeWidth,
                }}
              />
            </motion.div>
            <div style={{ margin: isMobile ? "10px" : "20px" }}></div>
            <motion.div ref={constraintsRef2}>
              <motion.div
                drag
                dragConstraints={constraintsRef2}
                style={{
                  backgroundColor: "#3b484f",
                  width: cubeWidth,
                  height: cubeWidth,
                }}
              />
            </motion.div>
          </Grid>
          <div style={{ margin: "10px" }}></div>
          <motion.div ref={constraintsRef3}>
            <motion.div
              drag
              dragConstraints={constraintsRef3}
              style={{
                fontFamily: "Lato, sans-serif !important",
                fontSize: isMobile ? "25px" : "45px",
                color: "white",
              }}
            >
              CIVILINGENJÖR
            </motion.div>
          </motion.div>
          <motion.div ref={constraintsRef4}>
            <motion.div
              drag
              dragConstraints={constraintsRef4}
              style={{
                fontFamily: "Barlow, sans-serif !important",
                fontWeight: "bold",
                fontSize: isMobile ? "30px" : "64px",
                color: "white",
              }}
            >
              MEDIETEKNIK
            </motion.div>
          </motion.div>
        </Grid>
      </BackgroundImage>
      <Grid
        container
        display="flex"
        flexDirection="column"
        alignItems="center"
        mx={{ xs: 2, lg: 0 }}
      >
        <Grid container>
          <Grid container maxWidth="lg" spacing={2} sx={{ marginBottom: 4 }}>
            <Grid
              xs={12}
              display="flex"
              flexDirection="column"
              alignItems="center"
            >
              <Typography
                paddingTop={5}
                color="black"
                variant="h2"
                textAlign="justify"
              >
                Vad är MT?
              </Typography>
              <Typography color="black" textAlign="center">
                Hej! Välkommen till sidan om Medieteknik, eller MT som vi kallar
                det. Vår utbildning heter Medieteknik eftersom den handlar om
                tekniken bakom de olika medierna, d.v.s. ljud, bild, video,
                spel, m.m. Medietekniks logotyp är två kvadrater (men vi brukar
                kalla dem kuber). Den orangea kuben representerar kreativitet
                och de mjuka ämnena i medieteknik, och den grå kuben
                representerar teknik och de hårda ämnena. Utöver detta är det
                stort fokus på problemlösning, vilket är en viktig förmåga som
                civilingenjör.
              </Typography>
              <StyledButton src="/about">Läs mer</StyledButton>
            </Grid>
          </Grid>
        </Grid>
        <Grid
          container
          display="flex"
          maxWidth="lg"
          justifyContent="space-around"
          columns={{ xs: 4, sm: 12, md: 14 }}
          columnSpacing={{ md: 5 }}
          rowSpacing={{ xs: 8 }}
        >
          {values.map((value, index) => {
            if (notSm) {
              return (
                <Grid
                  xs={4}
                  sm={4}
                  md={4}
                  key={index}
                  alignItems="center"
                  justifyContent="center"
                >
                  {/* TODO: center last item when screen is smaller*/}
                  <MtValues
                    description={value.description}
                    title={value.title}
                    image={value.image}
                  />
                </Grid>
              );
            } else {
              if (index !== values.length - 1) {
                return (
                  <Grid xs={4} sm={5} md={4} key={index} padding={0} margin={0}>
                    {/* TODO: center last item when screen is smaller*/}
                    <MtValues
                      description={value.description}
                      title={value.title}
                      image={value.image}
                    />
                  </Grid>
                );
              } else {
                return (
                  <Grid sm={5} key={index} mt={6} justifyContent="center">
                    {/* TODO: center last item when screen is smaller*/}
                    <MtValues
                      description={value.description}
                      title={value.title}
                      image={value.image}
                    />
                  </Grid>
                );
              }
            }
          })}
        </Grid>
        <Grid container>
          <ImageWithSummary
            imageSrc="/images/nollep6.jpg"
            direction="row"
            title="Studentliv"
          >
            <Grid
              sx={{
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
              }}
            >
              <Typography marginTop={3} textAlign="center">
                De flesta som pluggar här flyttar hemifrån för att komma till
                Norrköping och det kan kännas rätt läskigt att lämna allt man
                vuxit upp med. Men oroa dig inte, det som väntar här är vad de
                flesta på MT minns som den bästa delen av deras studietid:
                Nolleperioden, eller Nolle-P. Nolle-P heter så eftersom de nya
                eleverna inte börjar ettan innan sista dagen på Nolle-P. Efter
                Nolle-P finns det massor av{" "}
                <a
                  href="https://studentlivet.se/orbi-associations/"
                  style={{ color: "#EC6610", textDecoration: "underline" }}
                >
                  föreningar
                </a>{" "}
                att engagera sig i för att främja studentlivet.
              </Typography>
              <StyledButton src="/studentliv">Läs mer här</StyledButton>
            </Grid>
          </ImageWithSummary>
        </Grid>
      </Grid>
      <Grid md={12} display="flex" justifyContent="center">
        <WavyBackground bgColor="#13283c">
          <Grid display="flex" flexDirection="column" alignItems="center">
            <Carousel carouselItems={carouselItems} />
          </Grid>
        </WavyBackground>
      </Grid>
      <Grid
        container
        display="flex"
        flexDirection="column"
        alignItems="center"
        mx={{ xs: 2, lg: 0 }}
      >
        <Grid container>
          <ImageWithSummary
            imageSrc="/images/mtd2.jpg"
            direction="row-reverse"
            title="Medieteknikdagen"
          >
            <Grid
              sx={{
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
              }}
            >
              <Typography marginTop={3} textAlign="center">
                Medieteknikdagen är våran arbetsmarknadsdag och är ett ideellt
                arrangemang drivet av och för studenter. Syftet är att knyta
                kontakter mellan studenter, medietekniker ute i arbetslivet och
                företagen inom branschen. MTD är ett tillfälle för företag och
                studenter att inspirera, informera och integrera med varandra.
                Såväl företag som studenter får här en chans att visa det allra
                senaste inom medieteknik.
              </Typography>

              <StyledButton
                external={true}
                src="https://www.medieteknikdagen.se/"
              >
                Läs mer här
              </StyledButton>
            </Grid>
          </ImageWithSummary>
        </Grid>
      </Grid>
    </motion.div>
  );
};

export default Home;
