import { useContext } from "react";
import {
  Box,
  Button,
  Link,
  Typography,
  useMediaQuery,
  useTheme,
} from "@mui/material";
import Image from "next/image";
import Grid from "@mui/material/Unstable_Grid2";
import { MobileStateContext } from "../contexts/MobileContexts";
import { motion } from "framer-motion";
import type { NextPage } from "next";
import type { CarouselItem, Value } from "../utils/types";
import Head from "next/head";
import { useRef } from "react";
import { fadeInUp } from "../animations/constants";
import gruppbild from "../public/images/gruppbild.jpg";
import BackgroundImage from "../components/general/BackgroundImage";
import jsonValues from "../content/values.json";
import MtValues from "../components/home/mtValues";
import WavyBackground from "../components/general/WavyBackground";
import Carousel from "../components/general/Carousel";
import carouselImages from "../content/carouselItems.json";
import StyledButton from "../components/general/StyledButton";
import ImageWithSummary from "../components/general/ImageWithSummary";

const Home: NextPage = () => {
  const { isMobile, isIpad, isDesktop } = useContext(MobileStateContext);

  const theme = useTheme();

  const constraintsRef1 = useRef(null);
  const constraintsRef2 = useRef(null);
  const constraintsRef3 = useRef(null);
  const constraintsRef4 = useRef(null);

  const matchesSm = useMediaQuery(theme.breakpoints.down("md"));
  const notSm = useMediaQuery(theme.breakpoints.not("sm"));

  const values: Value[] = jsonValues;
  const carouselItems: CarouselItem[] = carouselImages;

  return (
    <motion.div
      // style={{
      //   backgroundImage: `url(${gruppbild.src})`,
      //   backgroundSize: "cover",
      // }}
      animate="animate"
      initial="initial"
      style={{ overflow: "hidden", background: "white" }}
    >
      <Head>
        <title>Civilingenjör i Medieteknik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <video autoPlay loop muted id="video">
        <source
          src={require(`../assets/introVideo.mp4`).default.src}
          type="video/mp4"
        />
      </video> */}
      <BackgroundImage imgSrc="/images/axels/styrelsen-6.jpg">
        {
          //TODO: This grid should cover entire page and contian all child grids
        }
        <Grid
          display="flex"
          flexDirection="column"
          alignItems="center"
          justifyContent="center"
          sx={{ width: "100%", height: "80vh", zIndex: 100 }}
        >
          <Grid
            container
            display="flex"
            alignItems="center"
            justifyContent="center"
          >
            <motion.div ref={constraintsRef1} variants={fadeInUp}>
              <motion.div
                drag
                dragConstraints={constraintsRef1}
                style={{
                  backgroundColor: "#EC6610",
                  width: "150px",
                  height: "150px",
                }}
              />
            </motion.div>
            <div style={{ margin: "20px" }}></div>
            <motion.div ref={constraintsRef2}>
              <motion.div
                drag
                dragConstraints={constraintsRef2}
                style={{
                  backgroundColor: "#3b484f",
                  width: "150px",
                  height: "150px",
                }}
              />
            </motion.div>
          </Grid>
          <div style={{ margin: "10px" }}></div>
          <motion.div ref={constraintsRef3}>
            <motion.div
              drag
              dragConstraints={constraintsRef3}
              style={{
                fontFamily: "Lato",
                fontSize: "45px",
              }}
            >
              CIVILINGENJÖR
            </motion.div>
          </motion.div>
          <motion.div ref={constraintsRef4}>
            <motion.div
              drag
              dragConstraints={constraintsRef4}
              style={{
                fontFamily: "Barlow",
                fontWeight: "bold",
                fontSize: "64px",
              }}
            >
              MEDIETEKNIK
            </motion.div>
          </motion.div>
        </Grid>
      </BackgroundImage>
      <Grid
        container
        spacing={2}
        paddingLeft={{ xs: 3, lg: 15 }}
        paddingRight={{ xs: 3, lg: 15 }}
        sx={{ marginBottom: 4 }}
      >
        <Grid
          xs={12}
          sx={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
          }}
        >
          <Typography
            paddingTop={5}
            color="black"
            variant="h2"
            textAlign="center"
          >
            Vad är MT?
          </Typography>
          <Typography color="black" textAlign="center">
            Hej! Välkommen till sidan om Medieteknik, eller MT som vi kallar
            det. Vår utbildning heter Medieteknik eftersom den handlar om
            tekniken bakom de olika medierna, d.v.s. ljud, bild, video, spel,
            m.m. Medietekniks logotyp är två kvadrater (men vi brukar kalla dem
            kuber). Den orangea kuben representerar kreativitet och de mjuka
            ämnena i medieteknik, och den grå kuben representerar teknik och de
            hårda ämnena. Utöver detta är det stort fokus på problemlösning,
            vilket är en viktig förmåga som civilingejör.
          </Typography>
          <StyledButton src="/about">Läs mer</StyledButton>
        </Grid>
      </Grid>
      <Grid
        container
        padding={5}
        alignItems={"center"}
        paddingLeft={{ xs: 3, lg: 15 }}
        paddingRight={{ xs: 3, lg: 15 }}
        spacing={6}
        columns={{ xs: 4, sm: 8, md: 12 }}
      >
        {values.map((value, index) => {
          if (notSm) {
            return (
              <Grid
                xs={4}
                sm={4}
                md={4}
                key={index}
                alignItems="center"
                justifyContent="center"
              >
                {/* TODO: center last item when screen is smaller*/}
                <MtValues
                  description={value.description}
                  title={value.title}
                  image={value.image}
                />
              </Grid>
            );
          } else {
            if (index !== values.length - 1) {
              return (
                <Grid
                  xs={4}
                  sm={4}
                  md={4}
                  key={index}
                  alignItems="center"
                  justifyContent="center"
                >
                  {/* TODO: center last item when screen is smaller*/}
                  <MtValues
                    description={value.description}
                    title={value.title}
                    image={value.image}
                  />
                </Grid>
              );
            } else {
              return (
                <Grid
                  sm={8}
                  key={index}
                  alignItems="center"
                  justifyContent="center"
                  paddingRight={23}
                  paddingLeft={23}
                >
                  {/* TODO: center last item when screen is smaller*/}
                  <MtValues
                    description={value.description}
                    title={value.title}
                    image={value.image}
                  />
                </Grid>
              );
            }
          }
        })}
      </Grid>
      <Grid container paddingTop={9} paddingBottom={9}>
        <ImageWithSummary
          imageSrc="/images/nollep6.jpg"
          direction="row"
          imgHeight="500px"
          imgWidth="700px"
        >
          <Grid
            sx={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
            }}
          >
            <Typography textAlign="center" variant="h2">
              Studentliv
            </Typography>
            <Typography marginTop={3} textAlign="center">
              De flesta som pluggar här flyttar hemifrån för att komma till
              Norrköping och det kan kännas rätt läskigt att lämna allt man
              vuxit upp med. Men oroa dig inte, det som väntar här är vad de
              flesta på MT minns som den bästa delen av deras studietid:
              Nolleperioden, eller Nolle-P. Nolle-P heter så eftersom de nya
              eleverna inte börjar ettan innan sista dagen på Nolle-P. Efter
              Nolle-P finns det massor av{" "}
              <a
                href="https://studentlivet.se/orbi-associations/"
                style={{ color: "#EC6610", textDecoration: "underline" }}
              >
                föreningar
              </a>{" "}
              att engagera sig i för att främja studentlivet.
            </Typography>
            <StyledButton src="/studentliv">Läs mer här</StyledButton>
          </Grid>
        </ImageWithSummary>
      </Grid>
      <Grid md={12} display="flex" justifyContent="center">
        <WavyBackground bgColor="#13283c">
          <Grid
            sx={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
            }}
          >
            <Carousel carouselItems={carouselItems} />
            <StyledButton src="/sektionen">Läs mer här</StyledButton>
          </Grid>
        </WavyBackground>
      </Grid>
      <Grid container paddingTop={9} paddingBottom={9}>
        <ImageWithSummary
          imageSrc="/images/mtd2.jpg"
          direction="row-reverse"
          imgWidth={"500px"}
          imgHeight={"500px"}
        >
          <Grid
            sx={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
            }}
          >
            <Typography textAlign="center" variant="h2">
              Medieteknikdagen
            </Typography>
            <Typography marginTop={3} textAlign="center">
              Medieteknikdagen är våran arbetsmarknadsdag och är ett ideellt
              arrangemang drivet av och för studenter. Syftet är att knyta
              kontakter mellan studenter, medietekniker ute i arbetslivet och
              företagen inom branschen. MTD är ett tillfälle för företag och
              studenter att inspirera, informera och integrera med varandra.
              Såväl företag som studenter får här en chans att visa det allra
              senaste inom medieteknik.
            </Typography>

            <StyledButton
              external={true}
              src="https://www.medieteknikdagen.se/"
            >
              Läs mer här
            </StyledButton>
          </Grid>
        </ImageWithSummary>
      </Grid>
    </motion.div>
  );
};

export default Home;
