import { useContext } from "react";
import {
  Box,
  Button,
  Link,
  Typography,
  useMediaQuery,
  useTheme,
} from "@mui/material";
import Image from "next/image";
import Grid from "@mui/material/Unstable_Grid2";
import { MobileStateContext } from "../contexts/MobileContexts";
import { motion } from "framer-motion";
import type { NextPage } from "next";
import type { CarouselItem, Value } from "../utils/types";
import Head from "next/head";
import { useRef } from "react";
import { fadeInUp } from "../animations/constants";
import gruppbild from "../public/images/gruppbild.jpg";
import BackgroundImage from "../components/general/BackgroundImage";
import jsonValues from "../content/values.json";
import MtValues from "../components/home/mtValues";
import WavyBackground from "../components/general/WavyBackground";
import Carousel from "../components/general/Carousel";
import carouselImages from "../content/carouselItems.json";
import StyledButton from "../components/general/StyledButton";
import ImageWithSummary from "../components/general/ImageWithSummary";

const Home: NextPage = () => {
  const { isMobile, isIpad, isDesktop } = useContext(MobileStateContext);

  const theme = useTheme();

  const constraintsRef1 = useRef(null);
  const constraintsRef2 = useRef(null);
  const constraintsRef3 = useRef(null);
  const constraintsRef4 = useRef(null);

  const matchesSm = useMediaQuery(theme.breakpoints.down("md"));
  const notSm = useMediaQuery(theme.breakpoints.not("sm"));

  const values: Value[] = jsonValues;
  const carouselItems: CarouselItem[] = carouselImages;

  return (
    <motion.div
      // style={{
      //   backgroundImage: `url(${gruppbild.src})`,
      //   backgroundSize: "cover",
      // }}
      animate="animate"
      initial="initial"
      style={{ overflow: "hidden", background: "white" }}
    >
      <Head>
        <title>Civilingenjör i Medieteknik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <video autoPlay loop muted id="video">
        <source
          src={require(`../assets/introVideo.mp4`).default.src}
          type="video/mp4"
        />
      </video> */}
      <BackgroundImage imgSrc={gruppbild.src}>
        {
          //TODO: This grid should cover entire page and contian all child grids
        }
        <Grid
          display="flex"
          flexDirection="column"
          alignItems="center"
          justifyContent="center"
          sx={{ width: "100%", height: "80vh", zIndex: 100 }}
        >
          <Grid
            container
            display="flex"
            alignItems="center"
            justifyContent="center"
          >
            <motion.div ref={constraintsRef1} variants={fadeInUp}>
              <motion.div
                drag
                dragConstraints={constraintsRef1}
                style={{
                  backgroundColor: "#EC6610",
                  width: "150px",
                  height: "150px",
                }}
              />
            </motion.div>
            <div style={{ margin: "20px" }}></div>
            <motion.div ref={constraintsRef2}>
              <motion.div
                drag
                dragConstraints={constraintsRef2}
                style={{
                  backgroundColor: "#3b484f",
                  width: "150px",
                  height: "150px",
                }}
              />
            </motion.div>
          </Grid>
          <div style={{ margin: "10px" }}></div>
          <motion.div ref={constraintsRef3}>
            <motion.div
              drag
              dragConstraints={constraintsRef3}
              style={{
                fontFamily: "Lato",
                fontSize: "45px",
              }}
            >
              CIVILINGENJÖR
            </motion.div>
          </motion.div>
          <motion.div ref={constraintsRef4}>
            <motion.div
              drag
              dragConstraints={constraintsRef4}
              style={{
                fontFamily: "Barlow",
                fontWeight: "bold",
                fontSize: "64px",
              }}
            >
              MEDIETEKNIK
            </motion.div>
          </motion.div>
        </Grid>
      </BackgroundImage>
      <Grid
        container
        spacing={2}
        paddingLeft={{ xs: 3, lg: 15 }}
        paddingRight={{ xs: 3, lg: 15 }}
      >
        <Grid xs={12}>
          <Typography
            paddingTop={5}
            color="black"
            variant="h2"
            textAlign="center"
          >
            Vad är MT?
          </Typography>
          <Typography color="black" textAlign="center">
            Hej! Välkommen till sidan om Medieteknik, eller MT som vi kallar
            det. I videon ovanför ser du några projekt som vi MT:are har gjort i
            olika kurser. Vår utbildning heter Medieteknik eftersom den handlar
            om tekniken bakom de olika medierna, d.v.s. ljud, bild, video, spel,
            m.m. Det låter väldigt brett, men i praktiken specialiserar vi oss
            på 3D-grafik och att visualisera information. Medietekniks logotyp
            är två kvadrater (men vi brukar kalla dem kuber): Den orangea kuben,
            som representerar kreativitet och de mjuka ämnena i medieteknik, och
            den grå kuben som representerar teknik och de hårda ämnena. Bland de
            kreativa kurserna tas ämnen som design, videoproduktion,
            användarvänlighet och interaktion mellan människa och teknik upp.
            Oftast är det programmering vi använder för att förverkliga våra
            idéer och programmeringen blir en av våra viktigaste färdigheter på
            arbetsmarknaden.
          </Typography>
        </Grid>
      </Grid>
      <Grid
        container
        padding={5}
        alignItems={"center"}
        paddingLeft={{ xs: 3, lg: 15 }}
        paddingRight={{ xs: 3, lg: 15 }}
        spacing={6}
        columns={{ xs: 4, sm: 8, md: 12 }}
      >
        {values.map((value, index) => {
          if (notSm) {
            return (
              <Grid
                xs={4}
                sm={4}
                md={4}
                key={index}
                alignItems="center"
                justifyContent="center"
              >
                {/* TODO: center last item when screen is smaller*/}
                <MtValues
                  description={value.description}
                  title={value.title}
                  image={value.image}
                />
              </Grid>
            );
          } else {
            if (index !== values.length - 1) {
              return (
                <Grid
                  xs={4}
                  sm={4}
                  md={4}
                  key={index}
                  alignItems="center"
                  justifyContent="center"
                >
                  {/* TODO: center last item when screen is smaller*/}
                  <MtValues
                    description={value.description}
                    title={value.title}
                    image={value.image}
                  />
                </Grid>
              );
            } else {
              return (
                <Grid
                  sm={8}
                  key={index}
                  alignItems="center"
                  justifyContent="center"
                  paddingRight={23}
                  paddingLeft={23}
                >
                  {/* TODO: center last item when screen is smaller*/}
                  <MtValues
                    description={value.description}
                    title={value.title}
                    image={value.image}
                  />
                </Grid>
              );
            }
          }
        })}
      </Grid>
      <Grid container paddingTop={9} paddingBottom={9}>
        {/* {matchesSm ? ( */}
        <Grid
          md={9}
          paddingLeft={{ xs: 3, lg: 15, md: 8 }}
          paddingRight={{ xs: 3, lg: 15 }}
          display="flex"
          flexDirection="column"
          alignItems="center"
        >
          <Typography textAlign="center" variant="h2">
            Studentliv
          </Typography>
          {isMobile && (
            <Image
              style={{ flex: 1 }}
              width={511 * 0.5}
              height={658 * 0.5}
              src={"/images/studentlivImage.png"}
              alt="Bild på studenter"
            />
          )}
          <Typography marginTop={3} textAlign="center">
            Under din studietid kommer det finnas gott om liv utanför skolan.
            LiU är välkänt för sitt studentliv och när du inte räknar
            flödesintegraler och mappar texturer kan du engagera dig i någon av
            våra många föreningar och styrelser eller kanske starta din egen.
            Vill du bygga ett spel? Springa marathon? Lira irländsk folkmusik?
            Du märker snabbt att MT alltid har gott om folk som vill engagera
            sig i ett kul projekt.
          </Typography>
          <StyledButton src="/studentliv">Läs mer här</StyledButton>
        </Grid>
        {!isMobile && (
          <Grid
            md={3}
            display="flex"
            justifyContent="flex-end"
            alignItems="center"
          >
            <Box
              position="relative"
              width={{ sm: 511 * 0.3, md: 511 * 0.4, lg: 511 * 0.5 }}
              height={{ sm: 658 * 0.3, md: 658 * 0.4, lg: 658 * 0.5 }}
            >
              <Image
                layout="fill"
                src={"/images/studentlivImage.png"}
                alt="Bild på studenter"
              />
            </Box>
          </Grid>
        )}
      </Grid>
      <Grid md={12} display="flex" justifyContent="center">
        <WavyBackground bgColor="#13283c">
          <Carousel carouselItems={carouselItems} />
        </WavyBackground>
      </Grid>
      <Grid container paddingTop={9} paddingBottom={9}>
        {/* <Grid
          md={9}
          paddingLeft={{ xs: 3, lg: 15 }}
          paddingRight={{ xs: 3, lg: 15 }}
          display="flex"
          flexDirection="column"
          alignItems="center"
        > */}
        <ImageWithSummary imageSrc="/images/mtd.jpg" direction="row">
          <Grid
            sx={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
            }}
          >
            <Typography textAlign="center" variant="h2">
              Medieteknikdagen
            </Typography>
            <Typography marginTop={3} textAlign="center">
              Medieteknikdagen är ett ideellt arrangemang drivet av och för
              studenter. Syftet är att knyta kontakter mellan studenter,
              medietekniker ute i arbetslivet och företagen inom branschen. I år
              har vi bytt namn från Medieteknikdagarna till Medieteknikdagen.
              MTD är ett tillfälle för företag och studenter att inspirera,
              informera och integrera med varandra. Såväl företag som studenter
              får här en chans att visa det allra senaste inom medieteknik.
            </Typography>
            {/* <Button
              variant="contained"
              component={"a"}
              LinkComponent={Link}
              href="https://www.medieteknikdagen.se/"
              color={"secondary"}
              sx={{ marginTop: 3 }}
            >
              Läs mer här
            </Button> */}
            <StyledButton
              external={true}
              src="https://www.medieteknikdagen.se/"
            >
              Läs mer här
            </StyledButton>
          </Grid>
        </ImageWithSummary>
        {/* <Image
            style={{ flex: 1 }}
            width={511 * 0.5}
            height={658 * 0.5}
            src={"/images/mtd.jpg"}
            alt="Bild på studenter"
          /> */}
        {/* </Grid> */}

        {/* <>
            <Grid
              md={3}
              spacing={6}
              display="flex"
              justifyContent="flex-start"
              alignItems="center"
            >
              <Box
                position="relative"
                width={{ sm: 511 * 0.3, md: 511 * 0.4, lg: 511 * 0.5 }}
                height={{ sm: 658 * 0.3, md: 658 * 0.4, lg: 658 * 0.5 }}
              >
                <Image
                  layout="fill"
                  src={"/images/mtd.jpg"}
                  alt="Bild på studenter"
                />
              </Box>
            </Grid>
            <Grid
              md={9}
              paddingRight={{ md: 8, lg: 15 }}
              display="flex"
              flexDirection="column"
              alignItems="center"
            >
              <Typography textAlign="center" variant="h2">
                Medieteknikdagen
              </Typography>
              <Typography textAlign="center">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit
                amet, consectetur adipiscing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua. Ut enim ad minim
                veniam, quis nostrud exercitation ullamco laboris nisi ut
                aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet,
                consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                nostrud exercitation ullamco laboris nisi ut aliquip ex ea
                commodo consequat.
              </Typography>
             
              <StyledButton
                external={true}
                src="https://www.medieteknikdagen.se/"
              >
                Läs mer här
              </StyledButton>
            </Grid>
          </> */}
      </Grid>
    </motion.div>
  );
};

export default Home;
