import Head from "next/head";
import type { NextPage } from "next";
import { useState, useContext } from "react";
import { Button, Grid, Typography } from "@mui/material";
import { motion } from "framer-motion";
import { MobileStateContext } from "../../contexts/MobileContexts";
// export default function PresentationPage() {
const PresentationPage: NextPage = () => {
  const { isMobile, isIpad, isDesktop } = useContext(MobileStateContext);
  return (
    <motion.div exit={{ opacity: 0 }} initial="initial" animate="animate">
      <Head>
        <title>Medieteknik.nu | Om MT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container sx={{ marginTop: "100px" }}>
        <Typography variant="h1">OM MT</Typography>
      </Grid>
      <Grid container></Grid>
    </motion.div>
  );
};

export default PresentationPage;
