import Head from "next/head";
import type { NextPage } from "next";
import { useState, useContext } from "react";
import { Button, Grid, Icon, IconButton, Typography } from "@mui/material";
import { motion } from "framer-motion";
import { MobileStateContext } from "../../contexts/MobileContexts";
import BackgroundImage from "../../components/general/BackgroundImage";
import gruppbild from "../../assets/gruppbild.jpg";
import { display } from "@mui/system";


import FacebookIcon from '@mui/icons-material/Facebook';
import InstagramIcon from '@mui/icons-material/Instagram';
import CreateOutlinedIcon from '@mui/icons-material/CreateOutlined';
import SchoolOutlinedIcon from '@mui/icons-material/SchoolOutlined';
import PeopleAltOutlinedIcon from '@mui/icons-material/PeopleAltOutlined';


// export default function PresentationPage() {
const PresentationPage: NextPage = () => {
  const { isMobile, isIpad, isDesktop } = useContext(MobileStateContext);
  // console.log("Mobile " + isMobile);
  // console.log("Ipad " + isIpad);
  // console.log("Desktop " + isDesktop);

  return (
    <motion.div exit={{ opacity: 0 }} initial="initial" animate="animate">
      <Head>
        <title>Medieteknik.nu | Om MT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      {/* <Grid container sx={{ marginTop: "100px" }}>
        <Typography variant="h1">OM MT</Typography>
      </Grid> */}

      {/* {isMobile ? <p>Mobile</p> : <p>desktop or ipad</p>}
      <Grid container></Grid>
      <Button variant="contained" color="secondary">
        Test
      </Button> */}

      <Grid container sx={{ justifyContent: "center", background: "red", marginBottom:"20px"}}>
        <BackgroundImage pageName="OM MT" imgSrc={gruppbild.src} />

        {/* ----------Civilingengör i Medieteknik ------------*/}
        <Grid container spacing={1} sx={{marginTop: "50px", padding: 9, paddingBottom:2, background:"white"}}>

            <Grid item xs={6} sx={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              textAlign: "center",
            }}>
              <Typography variant="h3" sx={{ margin: 2}}>
                Civilingejör i Medieteknik
              </Typography>

              <Typography sx={{margin: 2}}>
                Medieteknikområdet handlar om tekniken bakom medierna och
                om att omvandla informationsflöden så att de passar våra sinnen.
                Våra tidigare studenter jobbar med bland annat specialeffekter
                i Hollywoodfilmer, virtuella möbler för IKEA och spelutveckling. 
                Medieteknikområdet handlar om tekniken bakom medierna och om 

                <Grid item xs={12} sx={{ display: "flex", justifyContent: "center" }}>
                  <IconButton
                    color="secondary"
                    aria-label="upload picture"
                    component="label"
                  >
                    <FacebookIcon />
                  </IconButton>
                  <IconButton
                    color="secondary"
                    aria-label="upload picture"
                    component="label"
                  >
                    <InstagramIcon />
                  </IconButton>
                </Grid>

              </Typography>
            </Grid>

            <Grid item xs={6} sx={{ display: "flex", justifyContent: "right" }}>
              <img src={gruppbild.src} style={{ height: "90%", width: "80%", objectFit: "contain" }} />
            </Grid>
        </Grid>
        {/* ----------END Civilingengör i Medieteknik ------------*/}

        {/* ----------Kurser, masterkurser, studievägledare ------------*/}
        <Grid container sx={{justifyContent:"center", background: "#DEDEDE"}}>

          <Grid container sx={{marginTop: 5, marginBottom: 5, display:"flex", flexDirection:"row", justifyContent:"center"}}>
 
            <Grid item xs={4} md={3} sx={{
              alignItems: "center",
              textAlign: "center",
              padding: 2,
              }} >

            <Grid xs={10} sx={{display:"flex", justifyContent:"center",}}>
              <CreateOutlinedIcon color="secondary" fontSize="large"/>

              <Grid sx={{display:"flex", paddingLeft: 3}} >
                <Typography variant="h6" sx={{fontWeight: 'bold', paddingBottom:2}}> 
                  KURSER
                </Typography>
              </Grid>
            </Grid>

            <Typography sx={{marginBottom: 5}}>
              Medieteknikområdet handlar om tekniken bakom medierna och
              om att omvandla informationsflöden så att de passar våra sinnen.
              Våra tidigare studenter jobbar med bland annat specialeffekter
              i Hollywoodfilmer
            </Typography>
            <Button variant="contained" size="small">Läs mer</Button>

            </Grid>

            <Grid item xs={4} md={3} sx={{
              alignItems: "center",
              textAlign: "center",
              padding: 2,
            }} >

            <Grid xs={10} sx={{display:"flex", justifyContent:"center",}}>
              <SchoolOutlinedIcon color="secondary" fontSize="large"/>

              <Grid sx={{display:"flex", paddingLeft: 3}} >
                <Typography variant="h6" sx={{fontWeight: 'bold', paddingBottom:2}}>
                  Masterkurser
                </Typography>
              </Grid>
            </Grid>

              <Typography sx={{marginBottom: 5}}>
              Medieteknikområdet handlar om tekniken bakom medierna och
              om att omvandla informationsflöden så att de passar våra sinnen.
              Våra tidigare studenter jobbar med bland annat specialeffekter
              i Hollywoodfilmer
            </Typography>
            <Button variant="contained" size="small">Läs mer</Button>

            </Grid>

            <Grid item xs={4} md={3} sx={{
              alignItems: "center",
              textAlign: "center",
              padding: 2,
              }}>

            <Grid xs={10} sx={{display:"flex", justifyContent:"center",}}>
              <PeopleAltOutlinedIcon color="secondary" fontSize="medium"/>

              <Grid sx={{ paddingLeft: 3}} >
                <Typography variant="h6" sx={{fontWeight: 'bold', paddingBottom:2}}>
                  Studievägledare
                </Typography>
              </Grid>
            </Grid>

              <Typography sx={{marginBottom: 5}}>
              Medieteknikområdet handlar om tekniken bakom medierna och
              om att omvandla informationsflöden så att de passar våra sinnen.
              Våra tidigare studenter jobbar med bland annat specialeffekter
              i Hollywoodfilmer
            </Typography>

            <Button variant="contained" size="small">Läs mer</Button>


            </Grid>

          </Grid>
        </Grid>
        {/* ----------END Kurser, masterkurser, studievägledare ------------*/}

        {/* ----------Utlandsstudier ------------*/}
        <Grid container spacing={1} sx={{ padding: 9, paddingBottom:2, background:"white"}}>

          <Grid item xs={6} sx={{ display: "flex", justifyContent: "right" }}>
            <img src={gruppbild.src} style={{ height: "90%", width: "80%", objectFit: "contain" }} />
          </Grid>

            <Grid item xs={6} sx={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              textAlign: "center",
            }}>
              


              <Typography variant="h3" sx={{ margin: 2}}>
                Utlandsstudier
              </Typography>

              <Typography sx={{margin: 2}}>
                Medieteknikområdet handlar om tekniken bakom medierna och
                om att omvandla informationsflöden så att de passar våra sinnen.
                Våra tidigare studenter jobbar med bland annat specialeffekter
                i Hollywoodfilmer, virtuella möbler för IKEA och spelutveckling. 
                Medieteknikområdet handlar om tekniken bakom medierna och om 

                <Grid item xs={12} sx={{ display: "flex", justifyContent: "center", m: 4 }}>

                  <Button variant="contained"> Läs mer</Button>
                </Grid>

              </Typography>
            </Grid>
        </Grid>
        {/* ----------END Utlandsstudier ------------*/}

        {/* ----------Alumner ------------*/}
        <Grid container spacing={1} sx={{ padding: 6, justifyContent: "center", background:"blue"}}>

          <Grid sx={{textAlign:"center", margin: 2}}>
            <Typography variant="h3"  >Alumner</Typography>
            <Typography>sdnos idgo dbgodf ibgodbf oigbod fibgo</Typography>



          </Grid>


        </Grid>






      </Grid>




    </motion.div>
  );
};

export default PresentationPage;
