import Head from "next/head";
import type { NextPage } from "next";
import { useState, useContext } from "react";
import { Button, Grid, Typography } from "@mui/material";
import { motion } from "framer-motion";
import { MobileStateContext } from "../../contexts/MobileContexts";
import BackgroundImage from "../../components/general/BackgroundImage";
import gruppbild from "../../assets/gruppbild.jpg";
// export default function PresentationPage() {
const PresentationPage: NextPage = () => {
  const { isMobile, isIpad, isDesktop } = useContext(MobileStateContext);
  console.log("Mobile " + isMobile);
  console.log("Ipad " + isIpad);
  console.log("Desktop " + isDesktop);

  return (
    <motion.div exit={{ opacity: 0 }} initial="initial" animate="animate">
      <Head>
        <title>Medieteknik.nu | Om MT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BackgroundImage pageName="OM MT" imgSrc={gruppbild.src} />
      <Grid container sx={{ marginTop: "100px" }}>
        <Typography variant="h1">OM MT</Typography>
      </Grid>
      {isMobile ? <p>Mobile</p> : <p>desktop or ipad</p>}
      <Grid container></Grid>
      <Button variant="contained" color="secondary">
        Test
      </Button>
    </motion.div>
  );
};

export default PresentationPage;
