import Head from "next/head";
import Image from "next/image";
import type { NextPage } from "next";
import { useState } from "react";
import tempContent from "../tempContent.json";
import { Button, Grid, Typography } from "@mui/material";
import PresentationModal from "../../components/about/PresentationModal";
import PresentationCard from "../../components/about/PresentationCard";
import { motion } from "framer-motion";
import { fadeInUp } from "../../animations/constants";
import { Styrare } from "../../utils/types";
// export default function PresentationPage() {
const PresentationPage: NextPage = () => {
  const styrare: Styrare[] = tempContent.styrareContent;
  console.log(styrare);
  const [modalOpen, setModalOpen] = useState<boolean>(false);
  const [activeUser, setActiveUser] = useState<number>(0);

  function handleUserClick(index: number) {
    setActiveUser(index);
    setModalOpen(true);
  }

  return (
    <motion.div exit={{ opacity: 0 }} initial="initial" animate="animate">
      <Head>
        <title>Medieteknik.nu | Sektionen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container sx={{ marginTop: "100px" }}>
        <Typography variant="h1">SEKTIONEN</Typography>
      </Grid>
      <Grid container>
        {styrare.map((styr, index) => (
          <Grid item xs={4} key={index} sx={{ p: "20px", height: "100%" }}>
            <motion.div
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              variants={fadeInUp}
            >
              <PresentationCard
                user={styr}
                openInfo={() => handleUserClick(index)}
              />
            </motion.div>
          </Grid>
        ))}
      </Grid>
      {modalOpen && (
        <PresentationModal
          open={modalOpen}
          handleClose={() => setModalOpen(false)}
          user={styrare[activeUser]}
        />
      )}
    </motion.div>
  );
};

export default PresentationPage;
