import Head from "next/head";
import type { NextPage } from "next";
import { useState } from "react";
import tempContent from "../tempContent.json";
import { Container, Grid } from "@mui/material";
import PresentationModal from "../../components/about/PresentationModal";
import PresentationCard from "../../components/about/PresentationCard";
import { motion } from "framer-motion";
import { fadeInUp } from "../../animations/constants";
import { Styrare } from "../../utils/types";
import ImageWithSummary from "../../components/general/ImageWithSummary";
import BannerWithSummary from "../../components/general/BannerWithSummary";
import WavyBackground from "../../components/general/WavyBackground";
import Image from "next/image";

// export default function PresentationPage() {
const PresentationPage: NextPage = () => {
  const styrare: Styrare[] = tempContent.styrareContent;
  console.log(styrare);
  const [modalOpen, setModalOpen] = useState<boolean>(false);
  const [activeUser, setActiveUser] = useState<number>(0);

  function handleUserClick(index: number) {
    setActiveUser(index);
    setModalOpen(true);
  }

  return (
    <motion.div exit={{ opacity: 0 }} initial="initial" animate="animate">
      <Head>
        <title>Medieteknik.nu | Sektionen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Styrelsen */}

      <BannerWithSummary imageSrc={require("../../assets/gruppbild2.jpg")} title="Styrelsen" text="Hej! Vi är Medietekniksektionens styrelse under perioden 22/23. Vi representerar MT-eleverna gentemot LiU, verkar för en bättre arbetsmiljö för oss studenter och anordnar event för MT:are. Vi anordnar också föreläsningar där företag och alumner berättar om livet efter examen. Om du har ett förbättringsförslag eller om något inte känns rätt med studierna kan du alltid vända dig till oss!"/>

      {/* Mette & #3Cant */}

      <WavyBackground bgColor="#13283c" textColor="#FFF">
        <Container>
            <ImageWithSummary 
              direction="row-reverse"
              imageSrc={require("../../assets/3cant.jpg")} 
              title="3Cant" 
              text="3Cant är festeriet för civilinjengörerna i Norrköping. De arrangerar fester i alla dess slag bla bla bla bla."
              link="https://www.3cant.com/"
            />
            <ImageWithSummary 
              direction="row"
              imageSrc={require("../../assets/mette.jpg")} 
              title="METTE" 
              text="Mette är sektionens tjejförening som jobbar för att främja gemenskapen mellan alla tjejer och icke-binära på MT-programmet!"
              link="temp"
            />
        </Container>
      </WavyBackground>

      {/* Styrelse-Grid*/}

      <Grid container sx={{ maxWidth: "1200px", margin: "auto", padding: "50px 0"}}
      >
        {styrare.map((styr, index) => (
          <Grid item xs={6} md={3} key={index} sx={{ p: "20px", height: "100%" }}>
            <motion.div
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              variants={fadeInUp}
            >
              <PresentationCard
                user={styr}
                openInfo={() => handleUserClick(index)}
              />
            </motion.div>
          </Grid>
        ))}
      </Grid>

      {modalOpen && (
        <PresentationModal
          open={modalOpen}
          handleClose={() => setModalOpen(false)}
          user={styrare[activeUser]}
        />
      )}
    </motion.div>
  );
};

export default PresentationPage;
